# Generated by Django 2.1.2 on 2019-02-20 23:21

from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'permissions': (('can_create_amenities', 'Can Create Amenities'), ('can_delete_amenities', 'Can Delete Amenities')),
            },
        ),
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Answer To Evaluation',
                'verbose_name_plural': 'Answers to Evaluations',
                'permissions': (('can_answer_evaluation', 'Can Answer a Evaluation'),),
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('value_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('offers_made_count', models.IntegerField(default=0)),
                ('offers_used_count', models.IntegerField(default=0)),
                ('last_offer_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'permissions': (('can_view_bill', 'Can View Bill'), ('can_delete_bill', 'Can Delete Bill')),
            },
        ),
        migrations.CreateModel(
            name='BillMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_owner', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('leave_at', models.DateTimeField(blank=True, null=True)),
                ('couvert_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill member',
                'verbose_name_plural': 'Bill members',
                'permissions': (('can_create_bill_member', 'Can Create Bill Member'),),
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_uuid', models.CharField(max_length=65, unique=True)),
                ('status_payment', models.CharField(blank=True, choices=[('IN_ANALYSIS', 'IN_ANALYSIS'), ('CANCELLED', 'CANCELLED'), ('AUTHORIZED', 'AUTHORIZED'), ('OFFLINE_PENDING', 'OFFLINE_PENDING'), ('OFFLINE_APPROVED', 'OFFLINE_APPROVED'), ('OFFLINE_CANCELLED', 'OFFLINE_CANCELLED')], max_length=40, null=True)),
                ('status_updated', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_payment_moip', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('noruh_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('moip_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payment', to='register.Bill')),
            ],
            options={
                'verbose_name': 'Bill payment',
                'verbose_name_plural': 'Bill payments',
                'permissions': (('can_view_payment', 'Can View Payment'), ('can_change_status_payment', 'Can Change Status Payment'), ('can_accept_payment', 'Can Accpet Payment'), ('can_create_payment', 'Can Create Payment'), ('can_update_payment', 'Can Update Payment'), ('can_delete_payment', 'Can Delete Payment')),
            },
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Cousine type',
                'verbose_name_plural': 'Cousine types',
                'permissions': (('can_create_cuisinetype', 'Can Create Cuisine Type'), ('can_delete_cuisinetype', 'Can Delete Cuisine Type')),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('USER_MANAGER', 'Gerente'), ('USER_WAITER', 'GarÃ§om(nete)'), ('USER_KITCHEN', 'Cozinheiro(a)'), ('USER_DOOR_MAN', 'Atendente')], max_length=25, verbose_name='Tipo de UsuÃ¡rio')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'FuncionÃ¡rio',
                'verbose_name_plural': 'FuncionÃ¡rios',
                'permissions': (('can_create_employee', 'Can Create Employee'), ('can_view_employee', 'Can View Employee'), ('can_alter_employee', 'Can Alter Employee'), ('can_delete_employee', 'Can Delete Employee')),
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('geo_loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('enabled', models.BooleanField(default=True)),
                ('opened', models.BooleanField(default=True)),
                ('gps_restriction', models.BooleanField(default=False)),
                ('logo_url', models.ImageField(upload_to='', verbose_name='Photo')),
                ('featured', models.BooleanField(default=False)),
                ('offer_range_value', models.DecimalField(decimal_places=2, default=50.0, help_text='Valor usado para controlar as ofertas liberadas', max_digits=4)),
                ('offer_count_limit', models.PositiveIntegerField(default=10)),
                ('noruh_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pays_payment_tax', models.BooleanField(default=False)),
                ('moip_fee', models.DecimalField(decimal_places=2, default=Decimal('0.69'), max_digits=2)),
                ('payment_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0549'), max_digits=4)),
                ('taxe_service', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4)),
                ('taxe_couvert', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('amenities', models.ManyToManyField(related_name='establishments', to='register.Amenity')),
                ('cuisine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.CuisineType')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
                'permissions': (('can_create_establishment', 'Can Create Establishment'), ('can_update_description_establishment', 'Can Update Description Establishment'), ('can_update_amenities_establishment', 'Can Update Amenities Establishment'), ('can_update_taxes_establishment', 'Can Update Taxes Establishment'), ('can_update_couvert_taxe_establishment', 'Can Update Couvert Taxe Establishment'), ('can_update_functions_establishment', 'Can Update Functions Establishment'), ('can_update_location_establishment', 'Can Update Location Establishment'), ('can_update_opened', 'Can Update Opened'), ('can_view_establishment', 'Can View Establishment'), ('can_view_all_establishments', 'Can View All Establishments'), ('can_delete_establishment', 'Can Delete Establishment'), ('can_view_dashboard_from_establishment', 'Can View Dashboard From Establishment'), ('can_view_qr_codes', 'Can View QR Codes')),
            },
        ),
        migrations.CreateModel(
            name='EstablishmentEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Establishment Event',
                'verbose_name_plural': 'Establishment Events',
                'permissions': (('can_create_events', 'Can Create Events'), ('can_view_events', 'Can View Events'), ('can_delete_events', 'Can Change Events')),
            },
        ),
        migrations.CreateModel(
            name='EstablishmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='register.Establishment')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Establishment manager',
                'verbose_name_plural': 'Establishment managers',
            },
        ),
        migrations.CreateModel(
            name='EstablishmentOperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('dow', models.IntegerField(choices=[(6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Establishment operating hour',
                'verbose_name_plural': 'Establishment operating hours',
                'permissions': (('can_create_operating_hour', 'Can Create Operating Hours'), ('can_list_operating_hour', 'Can List Operating Hours'), ('can_update_operating_hour', 'Can Update Operating Hours'), ('can_delete_operating_hour', 'Can Delete Operating Hours')),
            },
        ),
        migrations.CreateModel(
            name='EstablishmentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Establishment photo',
                'verbose_name_plural': 'Establishment photos',
                'permissions': (('can_add_photo_establishment', 'Can Add Photo On Establishment'), ('can_delete_photo_establishment', 'Can Delete Photo On Establishment'), ('can_view_photo_establishment', 'Can View Photo On Establishment')),
            },
        ),
        migrations.CreateModel(
            name='EstablishmentPromotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=20, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Establishment Promotion',
                'verbose_name_plural': 'Establishment Promotions',
                'permissions': (('can_create_promocode', 'Can Create Promocode'), ('can_view_promotions', 'Can View Promocodes'), ('can_delete_promotions', 'Can Change Promocodes')),
            },
        ),
        migrations.CreateModel(
            name='EstablishmentStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(auto_now_add=True)),
                ('period_end', models.DateTimeField(null=True)),
                ('rating_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categorys',
                'permissions': (('can_create_category', 'Can Create Category'), ('can_view_category', 'Can View Category'), ('can_update_category', 'Can Update Category'), ('can_delete_category', 'Can Delete Category')),
            },
        ),
        migrations.CreateModel(
            name='ItemObservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Item Observation',
                'verbose_name_plural': 'Item Observations',
                'permissions': (('can_create_item_observation', 'Can Item Observation'), ('can_view_item_observation', 'Can Item Observation'), ('can_update_item_observation', 'Can Item Observation'), ('can_delete_item_observation', 'Can Item Observation')),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'permissions': (('can_create_menu', 'Can Create Menu'), ('can_view_menu', 'Can View Menu'), ('can_update_menu', 'Can Update Menu'), ('can_delete_menu', 'Can Delete Menu')),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('serve_up', models.PositiveIntegerField(default=1, verbose_name='Serve up')),
                ('preparation_time', models.TimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.ItemCategory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='register.Menu', verbose_name='Menu')),
                ('observations', models.ManyToManyField(to='register.ItemObservations')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'permissions': (('can_create_item_on_menu', 'Can Create Item On Menu'), ('can_view_item_on_menu', 'Can View Item On Menu'), ('can_change_item_on_menu', 'Can Change Item On Menu'), ('can_delete_item_on_menu', 'Can Delete Item On Menu')),
            },
        ),
        migrations.CreateModel(
            name='MenuOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='register.ItemCategory')),
            ],
            options={
                'verbose_name': 'Menu Offer',
                'verbose_name_plural': 'Menu Offer',
                'permissions': (('can_create_menu_offer', 'Can Create Menu Offer'), ('can_view_menu_offer', 'Can View Menu Offer'), ('can_update_menu_offer', 'Can Update Menu Offer'), ('can_delete_menu_offer', 'Can Delete Menu Offer')),
            },
        ),
        migrations.CreateModel(
            name='MoipWirecardAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, unique=True)),
                ('website', models.CharField(max_length=100, unique=True)),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('secret', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'APP Moip MoipWirecard',
                'verbose_name_plural': 'APP Moip Wirecards',
            },
        ),
        migrations.CreateModel(
            name='MoipWirecardCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(default='Establishment', max_length=50)),
                ('id_wirecard', models.CharField(blank=True, max_length=64, null=True)),
                ('login', models.CharField(blank=True, max_length=64, null=True)),
                ('access_token', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('number_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('street_number', models.CharField(blank=True, max_length=4, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('area_code', models.CharField(blank=True, max_length=3, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('number_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('issuer', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('link_account', models.CharField(blank=True, max_length=200, null=True)),
                ('set_password', models.CharField(blank=True, max_length=300, null=True)),
                ('channel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.MoipWirecardAPP')),
                ('establishment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Establishment WireCard',
                'verbose_name_plural': 'Establishment Wirecards',
                'permissions': (('can_create_wirecard', 'Can Create Wirecard'), ('can_view_wirecard', 'Can View Wirecard')),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STATUS_PENDING', 'STATUS_PENDING'), ('STATUS_REJECTED', 'STATUS_REJECTED'), ('STATUS_PREPARING', 'STATUS_PREPARING'), ('STATUS_DONE', 'STATUS_DONE')], default='STATUS_PENDING', max_length=25)),
                ('value_order', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='register.Bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.MenuItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'permissions': (('can_change_order_status', 'Can Change Order Status'), ('can_view_order', 'Can View Order'), ('can_change_order', 'Can Change Order'), ('can_create_order', 'Can Create Order')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=register.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('average_value_spent', models.FloatField(default=0.0)),
                ('visited_establishments_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('STATUS_PENDING', 'STATUS_PENDING'), ('STATUS_REQUESTED', 'STATUS_REQUESTED')], default='STATUS_PENDING', max_length=25)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'permissions': (('can_view_status_request', 'Can View Status Request'), ('can_change_status_request', 'Can Change Status Request')),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'permissions': (('can_create_table', 'Can Create Table'), ('can_view_table', 'Can View Table'), ('can_update_table', 'Can Update Table'), ('can_delete_table', 'Can Delete Table')),
            },
        ),
        migrations.CreateModel(
            name='TableZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_zone', to='register.Establishment')),
            ],
            options={
                'verbose_name': 'Table zone',
                'verbose_name_plural': 'Tables zones',
                'permissions': (('can_create_table_zone', 'Can Create Table Zone'), ('can_view_table_zone', 'Can View Table Zone'), ('can_change_table_zone', 'Can Change Table Zone'), ('can_desactive_table_zone', 'Can Desactive Table Zone'), ('can_delete_table_zone', 'Can Delete Table Zone')),
            },
        ),
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_four_digits', models.CharField(max_length=4)),
                ('brand_card', models.CharField(max_length=50)),
                ('id_moip_card', models.CharField(max_length=40)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('type_doc', models.CharField(blank=True, max_length=4, null=True)),
                ('number_doc', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'User Credit Card',
                'verbose_name_plural': 'Users Credit Cards',
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moip_user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('moip_user_token', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'Users Payments',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'Users profile',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('food', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('service', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.BillMember')),
            ],
            options={
                'verbose_name': 'User rating',
                'verbose_name_plural': 'User ratings',
                'permissions': (('can_delete_evaluation', 'Can Delete Evaluation'), ('can_view_evaluation', 'Can View Evaluation')),
            },
        ),
        migrations.AddField(
            model_name='usercreditcard',
            name='user_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to='register.UserPayment'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='register.TableZone'),
        ),
        migrations.AddField(
            model_name='request',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Table'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='register.MenuOffer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment', verbose_name='Estabelecimento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='UsuÃ¡rio'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.EstablishmentPromotions'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='user_moip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.UserPayment'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customers',
            field=models.ManyToManyField(through='register.BillMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment'),
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Table'),
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='register.Establishment'),
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_answer', to='register.UserRating'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('bill', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('establishment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('menu', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('establishment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('establishment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='establishmentoperatinghours',
            unique_together={('establishment', 'dow')},
        ),
        migrations.AlterUniqueTogether(
            name='establishmentmanager',
            unique_together={('establishment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='answerevaluation',
            unique_together={('evaluation', 'establishment')},
        ),
    ]
