# Generated by Django 2.1.2 on 2019-02-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='status_payment',
            field=models.CharField(blank=True, choices=[('IN_ANALYSIS', 'Sob anÃ¡lise'), ('CANCELLED', 'Cancelado'), ('AUTHORIZED', 'Autorizado'), ('OFFLINE_PENDING', 'Offline Pendente'), ('OFFLINE_APPROVED', 'Offline Aprovado'), ('OFFLINE_CANCELLED', 'Offline Cancelado')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='register.MenuOffer'),
        ),
    ]
