# Generated by Django 2.1.4 on 2019-03-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190227_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_create_employee', 'Can Create Employee'), ('can_view_employee', 'Can View Employee'), ('can_alter_employee', 'Can Alter Employee'), ('can_delete_employee', 'Can Delete Employee')), 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='status_payment',
            field=models.CharField(blank=True, choices=[('IN_ANALYSIS', 'Sob análise'), ('CANCELLED', 'Cancelado'), ('AUTHORIZED', 'Autorizado'), ('OFFLINE_PENDING', 'Offline Pendente'), ('OFFLINE_APPROVED', 'Offline Aprovado'), ('OFFLINE_CANCELLED', 'Offline Cancelado')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('USER_MANAGER', 'Gerente'), ('USER_WAITER', 'Garçom(nete)'), ('USER_KITCHEN', 'Cozinheiro(a)'), ('USER_DOOR_MAN', 'Atendente')], max_length=25, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='establishmentmanager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
