# Generated by Django 2.1.4 on 2019-03-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190308_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_change_order_status', 'Can Change Order Status'), ('can_view_order', 'Can View Order'), ('can_change_order', 'Can Change Order'), ('can_create_order', 'Can Create Order')), 'verbose_name': 'Ordem', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='establishmentoperatinghours',
            name='dow',
            field=models.IntegerField(choices=[(6, 'Domingo'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')]),
        ),
    ]
