# Generated by Django 2.1.2 on 2019-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190308_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unspecified', 'Unspecified')], max_length=25, null=True),
        ),
    ]
