# Generated by Django 2.1.2 on 2019-03-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190314_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='observations',
            field=models.ManyToManyField(blank=True, to='register.ItemObservations'),
        ),
    ]
