# Generated by Django 2.1.4 on 2019-03-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20190314_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('GENDER_MALE', 'GENDER_MALE'), ('GENDER_FEMALE', 'GENDER_FEMALE'), ('GENDER_OTHER', 'GENDER_OTHER'), ('GENDER_UNSPECIFIED', 'GENDER_UNSPECIFIED')], max_length=25, null=True),
        ),
    ]
