# Generated by Django 2.1.4 on 2019-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20190314_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('GENDER_MALE', 'GENDER_MALE'), ('GENDER_FEMALE', 'GENDER_FEMALE'), ('GENDER_OTHER', 'GENDER_OTHER')], max_length=25, null=True),
        ),
    ]
