# Generated by Django 2.1.2 on 2019-03-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20190314_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='observation',
        ),
    ]
