# Generated by Django 2.1.4 on 2019-03-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_remove_bill_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'permissions': (('can_create_establishment', 'Can Create Establishment'), ('can_update_description_establishment', 'Can Update Description Establishment'), ('can_update_amenities_establishment', 'Can Update Amenities Establishment'), ('can_update_taxes_establishment', 'Can Update Taxes Establishment'), ('can_update_couvert_taxe_establishment', 'Can Update Couvert Taxe Establishment'), ('can_update_offer_range_value', 'Can Update Offer Range Value Establishment'), ('can_update_functions_establishment', 'Can Update Functions Establishment'), ('can_update_location_establishment', 'Can Update Location Establishment'), ('can_update_opened', 'Can Update Opened'), ('can_view_establishment', 'Can View Establishment'), ('can_view_all_establishments', 'Can View All Establishments'), ('can_delete_establishment', 'Can Delete Establishment'), ('can_view_dashboard_from_establishment', 'Can View Dashboard From Establishment'), ('can_view_qr_codes', 'Can View QR Codes')), 'verbose_name': 'Establishment', 'verbose_name_plural': 'Establishments'},
        ),
    ]
