# Generated by Django 2.1.4 on 2019-03-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20190318_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='establishmentmanager',
            unique_together=set(),
        ),
    ]
