# Generated by Django 2.1.4 on 2019-03-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20190318_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmanager',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='register.Establishment'),
        ),
    ]
