# Generated by Django 2.1.2 on 2019-03-20 18:30

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20190318_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=register.models.decode_files, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='logo_url',
            field=models.ImageField(upload_to=register.models.decode_files, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='establishmentphoto',
            name='photo',
            field=models.ImageField(upload_to=register.models.decode_files),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(upload_to=register.models.decode_files, verbose_name='Photo'),
        ),
    ]
