# Generated by Django 2.1.4 on 2019-03-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20190322_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.UserCreditCard'),
        ),
    ]
