# Generated by Django 2.1.4 on 2019-04-01 13:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_billpayment_credit_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCompensations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Offline Compensation',
                'verbose_name_plural': 'Offlie Compensations',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='offline_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.02'), max_digits=2),
        ),
        migrations.AddField(
            model_name='offlinecompensations',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Establishment'),
        ),
    ]
