# Generated by Django 2.1.4 on 2019-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20190401_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinecompensations',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
