# Generated by Django 2.1.4 on 2019-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20190402_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinecompensations',
            options={'verbose_name': 'Offline Compensation', 'verbose_name_plural': 'Offline Compensations'},
        ),
        migrations.AddField(
            model_name='offlinecompensations',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offlinecompensations',
            name='month',
            field=models.IntegerField(),
        ),
    ]
