# Generated by Django 2.1.4 on 2019-04-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20190402_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlinecompensations',
            old_name='date',
            new_name='date_compensation',
        ),
    ]
