# Generated by Django 2.1.4 on 2019-05-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20190402_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_os',
            field=models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=25, null=True),
        ),
    ]
