# Generated by Django 2.1.4 on 2019-05-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_profile_device_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='user',
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bill_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.BillMember'),
        ),
    ]
