# Generated by Django 2.1.4 on 2019-05-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_tokenrecoverpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='moipwirecardcustomer',
            name='business_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='moipwirecardcustomer',
            name='description_activity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='moipwirecardcustomer',
            name='number_cnae',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='moipwirecardcustomer',
            name='number_cnpj',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='moipwirecardcustomer',
            name='opening_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
